/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  WebresortsCheckbox as WebresortsCheckbox
} from './components/webresorts-checkbox/webresorts-checkbox';

declare global {
  interface HTMLWebresortsCheckboxElement extends WebresortsCheckbox, HTMLStencilElement {
  }
  var HTMLWebresortsCheckboxElement: {
    prototype: HTMLWebresortsCheckboxElement;
    new (): HTMLWebresortsCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    "webresorts-checkbox": HTMLWebresortsCheckboxElement;
  }
  interface ElementTagNameMap {
    "webresorts-checkbox": HTMLWebresortsCheckboxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "webresorts-checkbox": JSXElements.WebresortsCheckboxAttributes;
    }
  }
  namespace JSXElements {
    export interface WebresortsCheckboxAttributes extends HTMLAttributes {
      checked?: boolean;
      disabled?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
